### ISSUE TITLE
Feedback / instruções de instalação

### ISSUE THREAD

**Issue by rodrigoamaral** [erickmendonca/gdg-django-lab#1]
@erickmendonca Senti falta somente de slides com as instruções de instalação do Python+Django. Pretende usar algum serviço online ou a instalação vai ser local na máquina de cada participante? De qualquer modo, seria bom deixar registrado nos slides o procedimento básico de instalação para a as plataformas mais comuns ou pelo menos um referência para consulta.

No mais tá show de bola, vai ser massa! :+1:

**Comment by erickmendonca** [comment]
O pessoal vai usar o nitrous.io na hora para evitar perder tempo. Só clicar
no botão hack :-)

Acho que podemos deixar um slide de referência. :-)
